data:
  dataset_path: "/home/jackson/LLaMA-Factory/notebook/cache/allenai___tulu-3-sft-mixture"
  tokenizer_path: "/tmp2/share_data/google-gemma-9b-it"
  split_ratio: 0.1
  subset: "train[:400000]"
  remove_columns_from_train: true

model:
  model_path: "/tmp2/share_data/google-gemma-9b-it/"
  device: "cuda:0"
  distill_layer_idx: [1,3,5,7,9]
  checkpoint_dir: "./checkpoints_13579"

training:
  lr: 1e-4
  num_epochs: 3
  save_interval: 10000
  eval_interval: 70000
  feature_dim: 64

logging:
  log_dir: "./logs"
  level: "INFO"
